### ISSUE TITLE
2015 我的年终小结，2016 期待中

### ISSUE THREAD

**Issue by wsdjeg** [winter-fall/Bye2015Hi2016#3]
### 工作

 医疗器械销售 15年上半年指标完成 下半年因私调回本地，过度一切正常 敲代码只是我的业余爱好，但其实我也很想找这方面工作。只是在二线城市，没有找到合适的机会。
### 学习
1. JAVA基础：javaSE Oracle(SQL,PL/SQL) JDBC
2. WEB基础：JavaScript JQuery AJAX
3. JavaWeb 以及 常见框架

**搭建团队进销存内部网站系统**

Android 深入学习

**销售数据分析app以及进销存app简单实现，方便平时订单管理，以及客户库存管理**
### 其他

开源项目
Dotfiles
1. [vim java 开发环境搭建](https://github.com/wsdjeg/dotfiles)
2. [vim-javacomplete2 项目测试及部分维护](https://github.com/artur-shaik/vim-javacomplete2)
3. [JavaUnit.vim](https://github.com/wsdjeg/JavaUnit.vim) 
4. [Mysql.vim](https://github.com/wsdjeg/Mysql.vim)

TODO
- [x] neovim job_control 
- [x] java asynchronous syntax checking in neovim
- [ ] elixir 
- [ ] python 
- [ ] lua

**Comment by cxyxlxdm** [comment]
A good plan!👍👍👍

**Comment by BinaryHB** [comment]
诶，同学，我之前也是医药销售，哈哈。

**Comment by wsdjeg** [comment]
Good night 2015!
