### ISSUE TITLE
Be a happier myself

### ISSUE THREAD

**Issue by BinaryHB** [winter-fall/Bye2015Hi2016#37]
Almost two years ago, I came to Beijing, hoping to start a brand new life of mine.

A former channel sales in pharmaceutical industry, who's major in Biological Engineering back to college, I went more and more depressed in some situations, as reluctantly to drink excess white whines, or putting on this fake mask to act like you loved the job.

Honestly, I really hate those traditional society rules. And I was extremely exhausted at that time especially the mental way.

Without not a bit experience of coding, I registered this sort of temporary training school for 4 months. After finished study at there, I came across with this big swing of  either cheated on my resume or not. I held to it at the end. I am for sure not the first one to do things that worthy of respect, and also for sure not the first one to give up themselves.

So I ended up with two offers, 4k salary but must go for trips often, and 3k salary but I can stay here. I naturally picked the second option.

Still, this company was not the place where my Internet journey starts. Just before I became its full-time employee, I left it for a very small startup which struggled for its series A venture yet to follow, at where I forced myself to grow up rapidly in pain but no in vain. Overworking through like two entire months, our boss got the money we needed. Then I must admitted that my status imperceptibly slides toward the comfortable zone.

Of course, I got a hell lot of skills to learn on Android development, but you see, human being is always lazy and stinging to procrastination and not to mention a ordinary people as I am. After the beginning of 2015, I felt like slowing down and however not doing anything to reverse it. 

Then I met this girl. Had Being single for 26 years, I was not very obsessed with her at first. Women, who is very independent and has their own perspective about what's happening in the world, appeal a great attraction to me. We discussed of a idea on education very late at night and seemly nobody wanted to go to sleep.

You may already guessed that it wasn't went out.

Due to my not impatience and maybe sort of dull sense on figuring out how girls are thinking, we kept this distance between us and stuck at the friend zone. She maybe a right girl at the right time, pitifully I was not fully prepared then. Further more, afraid of be the first one to commit sacrifice and who begged to be loved, I consider that only if interactions go back and forth between us is the right phrase where real relationship could begins. So the future ones are.

Gladly I determined to be a better person, cause she made me wanna be a better man.

I set my goal to go for studying Computer Science at US two years from now. I set plans to go through GOEFL and GRE tests. I set myself to talk with friends out there in English.

And I found a great new job two months ago. I got excellent pals here to encourage me, and my own mentor to help me. I am less anxious now and more positively stressful to release my energy and potential.

Surprisingly, I even got a cat. According to our HR who bring him to me, he is homeless outside in this cold winter. And the name is fat tiger given by my HR as well. It turns out that he is very healthy and docile. 

Meanwhile, The dumbfounding outcome is that I sleeps more time than usual. Guess I relieve in someway from the bad past.

One more thing, I want to express my grateful gratitude to some people, Here it goes:

Thanks to @大猫布丁, who wrote answers about Beijing GDG in Zhihu.com and I'm very happy to be one member of it later.

Thanks to @Trinea @daimajia @stormzhang, whose historic work guided and inspired me when I was on the road of Android Developing.

Thanks to @wennyyuan, who gave me a lot help when I wanna change my job and I finally fortunately settled down as a colleague of hers.

P.S. Merry Christmas to all of you, and hope you all will enjoy a greater life.

**Comment by liaohuqiu** [comment]
Man, keep going! :beers:

**Comment by BinaryHB** [comment]
@liaohuqiu Cheers, buddy! 🍺

**Comment by Trinea** [comment]
@BinaryHB :beers:

**Comment by stormzhang** [comment]
@BinaryHB Just do it!

**Comment by 2022happynew** [comment]
cool
