### ISSUE TITLE
Goodbye 2015, hello 2016~ @drakeet

### ISSUE THREAD

**Issue by drakeet** [winter-fall/Bye2015Hi2016#48]
2015 啊，最重要的… 嗯，当然是和老婆大人在一起的那些时光了，哈哈哈！

事情零零碎碎发生太多，这一年经历了创业、做产品，经历了5次到北京，到过上海，三亚；第二年休学；学会了游泳，亲历了下雪；看了数不清的电影，听了很多遍的牡丹亭外…

创业和工作都十分不容易。年末的时候拿到了锤子科技的 offer 差点就去了北京工作，那时已经心里打定主意无论如何一定要去了，锤子算是我的一个心愿，但最后还是留在了厦门。在这边还有机会，有难得的机遇，有特别想干、有决心、共同认识能够相互弥补的朋友，有真切帮助我们的人，有逐渐成型、团结的团队。所以还是很高兴能够继续创业，我终究不想一辈子默默当个程序猿，想证明一些事情，想做出我们自己的产品… 在开发和参与做产品的过程中，也学会了很多，不再那么固执己见，能够接受和理解很多。学着带团队，创建团队技术环境，尽量照顾大家，学着控制自己纠正自己，学会反思和改正，希望能一起走得更远走到美好，无怨无悔。

在北京的日子，见了代码家，那时我还很幼稚，但家家最后和我说希望我每次去北京如果可以都能去找他，特别感动，也见了扔物线朱凯哥，特别可爱、亲切，也感谢 Flipboard 各位的招待。见了马琳，马琳陪我在接近零度的北京度过了两个夜晚，送了我两本书，都特别好… 万千世界里，很高兴认识大家！

独立开发了几款个人应用，获得了算是十分多的打赏或称捐赠，非常感谢所有给过我支持的朋友！也十分抱歉到下半年特别是年末，一直没空去大力优化一些我的开源库和应用，来年希望能够逐渐把这些项目更好地优化起来，希望能够有空把构思的更多好用好玩的项目实现了。

**Comment by androidmalin** [comment]
那天看见了drakeet本人，好兴奋。南方的小孩，好清秀，而且很帅气，堪比TFboy。😘

**Comment by XhinLiang** [comment]
陪了两晚？
你居然……

**Comment by Rkhcy** [comment]
加油

**Comment by wozuihighwa** [comment]
两月前面试一家公司，面试官谈到一个年纪很小动画做的很棒，然后去了锤子，估计说的就是你把= =。

**Comment by iwgang** [comment]
厦门是个好地方...

**Comment by tianshaokai** [comment]
加油啊

**Comment by ryanhoo** [comment]
@androidmalin 你老是陪睡啊~
